Serialize/Deserialize multishape
cubzh/cubzh pull request #26
Opened 2022-10-18 09:39 UTC by caillef

2022-10-18 10:45 UTC, ArthurVoxowl requested changes
There is an issue in `serialization_v6_save_shape_as_buffer` as well as a number of minor syntax tweaks, please check the comments!

You also need to add a `case P3S_CHUNK_ID_NB_SHAPES:` in the switch in  `serialization_v6_get_preview_data`, so it can skip the chunk correctly when looking for the preview

2022-10-18 10:45 UTC, ArthurVoxowl commented on core/serialization_v6.c
> +                free(shapes);
Remove this (see previous comment)

2022-10-18 10:45 UTC, ArthurVoxowl commented on core/serialization_v6.c
> +                memset(shapes, 0, nbShapes * sizeof(*shapes));
Please use `sizeof(Shape*)` for clarity, this line and the line above

2022-10-18 10:45 UTC, ArthurVoxowl commented on core/serialization_v6.c
> +                memcpy(shapeId, cursor, sizeof(*shapeId));
Use `sizeof(uint32_t)` for clarity, the way we advance cursor is also based on the type. Overall, please use `sizeof(type)` in every similar line below

2022-10-18 10:45 UTC, ArthurVoxowl commented on core/serialization_v6.c
> +    *uncompressedSize = sizeof(nbShapes);
Use `sizeof(uint32_t)`

2022-10-18 10:45 UTC, ArthurVoxowl commented on core/serialization_v6.c
>          ok = write_preview_chunk_in_buffer(buf + cursor, previewData, previewDataSize, &cursor);
Before writing preview here, you should be writing `nbShapesCompressedDataSize` into destination buffer `buf` using eg. `write_compressed_chunk_in_buffer` or a similar function

2022-10-20 14:26 UTC, aduermael reviewed
A few comments on the file format.

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +    Chunk 'NB_SHAPES' : N, optional
We don't need this one. We'll just count shapes while processing file.

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +1        | byte       | p3s compression method : 0 (none), 1 (zip), 2 (count)
`count` is not a compression method, it just indicated the number of supported compression methods in the enum. We only support 0 (none) or 1 (zip) for now.

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +4        | uint       | total size
Maybe we should precise that this is the total size of data(compressed or not) coming after this number. (but the way, it's a `uint32_t`)

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +    SubChunk 'SHAPE_BAKED_LIGHTING' : optional
`SHAPE_PALETTE` SubChunk missing.

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +1        | byte       | chunk id
byte -> uint8

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +4        | int        | num bytes of chunk content (N)
int -> uint32

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +1        | byte       | is compressed
byte -> uint8 (0: not compressed - 1: compressed)

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +4        | int        | num bytes of chunk content uncompressed (M)
int -> uint32

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +4 x N    | int        | (r, g, b, alpha) : 1 byte for each entry
int -> uint8 x 4
not 4 x N (would be 4 times too much) - each color is 4 bytes

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +1 x N    | bool       | emissive flag
let's use uint8s instead of bools

2022-10-20 14:26 UTC, aduermael commented on cubzh-file-format-3zh.txt
> +    Chunk 'SHAPE' / Chunk 'OBJECT'
SHAPE is also optional. 
A file could only contain a PALETTE

2022-11-02 15:07 UTC, ArthurVoxowl requested changes

2022-11-02 15:07 UTC, ArthurVoxowl commented on core/serialization.c
> -        shape_shrink_box(shape);
You added this call inside `serialization_load_resources_v6`, but it is now missing for a v5 shape. You could add it in `serialization_v5_load_shape`

2022-11-02 15:07 UTC, ArthurVoxowl commented on core/serialization.c
>      // shrink box once all blocks were added to update box origin
Please remove this comment if the associated code was removed (or move it where the new calls are done)

2022-11-04 11:02 UTC, aduermael approved these changes
Looks good to me!
Thanks @caillef!

2022-11-04 13:16 UTC, ArthurVoxowl approved these changes

2022-11-04 13:17 UTC, merged