Core tests: shape
cubzh/cubzh pull request #40
Opened 2022-10-26 16:02 UTC by XLegland

2022-11-18 14:10 UTC, XLegland commented
/format

2022-11-18 14:35 UTC, XLegland commented
/format

2022-11-23 10:09 UTC, M0UTOO requested changes
There are some minors changes, but some of it are maybe not even required. Apart from that the rest of if lgtm 👍

2022-11-23 10:31 UTC, XLegland commented on core/tests/test_shape.h
> +void test_shape_release(void) {
Actually the shape is freed at the 2nd release, it releases its transform and then the transform frees its shape, in `_transform_free`:
```c
    switch (transform_get_type(t)) {
        case ShapeTransform: // Lua Shapes freed here
            shape_free((Shape *)transform_get_ptr(t));
            t->ptr = NULL;
            break;
        default:
            break;
    }
```

2022-11-23 10:34 UTC, M0UTOO approved these changes

2022-11-23 10:35 UTC, merged